---
- name: Install SonarQube with PostgreSQL
  hosts: sonarqube_servers
  become: yes
  
  pre_tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present
      tags: postgresql
    
    - name: Start PostgreSQL
      systemd:
        name: postgresql
        state: started
        enabled: yes
      tags: postgresql
    
    - name: Configure PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ sonar_db_name }}"
        owner: "{{ sonar_db_user }}"
      tags: postgresql
    
    - name: Configure PostgreSQL user
      become_user: postgres
      postgresql_user:
        name: "{{ sonar_db_user }}"
        password: "{{ sonar_db_password }}"
        role_attr_flags: "SUPERUSER,CREATEDB"
      tags: postgresql
  
  roles:
    - role: sonarqube
      tags: sonarqube
  
  post_tasks:
    - name: Wait for SonarQube to start
      wait_for:
        port: 9000
        delay: 10
        timeout: 300
      tags: sonarqube
    
    - name: Display SonarQube URL
      debug:
        msg: "SonarQube installed! Access at: http://{{ ansible_host }}:9000"
      tags: sonarqube